import AppKit
import Observation
import SwiftData

@Observable
class ClipboardMonitor {
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int = 0
    private var timer: DispatchSourceTimer?
    private var modelContext: ModelContext?
    private var transformEngine: TransformEngine?

    let maxItems: Int = 100

    private let ignoredTypes = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func setModelContext(_ context: ModelContext) {
        self.modelContext = context
    }

    func setTransformEngine(_ engine: TransformEngine) {
        self.transformEngine = engine
    }

    func start() {
        let queue = DispatchQueue(label: "com.clipass.monitor", qos: .utility)
        timer = DispatchSource.makeTimerSource(queue: queue)
        timer?.schedule(deadline: .now(), repeating: .milliseconds(500))
        timer?.setEventHandler { [weak self] in
            self?.poll()
        }
        timer?.resume()
    }

    func stop() {
        timer?.cancel()
        timer = nil
    }

    private func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // Check for ignored types (password managers, etc.)
        if let types = pasteboard.types {
            for type in types {
                if ignoredTypes.contains(type.rawValue) {
                    return // Skip secure content
                }
            }
        }

        guard let content = pasteboard.string(forType: .string) else { return }

        let sourceApp = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        DispatchQueue.main.async { [weak self] in
            guard let self = self, let context = self.modelContext else { return }

            // Apply transforms if engine is available
            var transformedContent = content
            if let engine = self.transformEngine {
                transformedContent = engine.transform(content, sourceApp: sourceApp)
            }

            // Update clipboard if content was transformed
            if transformedContent != content {
                self.pasteboard.clearContents()
                self.pasteboard.setString(transformedContent, forType: .string)
                // Update lastChangeCount to avoid re-polling our own change
                self.lastChangeCount = self.pasteboard.changeCount
            }

            let item = ClipboardItem(
                content: transformedContent,
                sourceApp: sourceApp,
                timestamp: Date()
            )

            context.insert(item)

            // Prune old items if exceeding maxItems
            self.pruneOldItems(context: context)

            try? context.save()
        }
    }

    private func pruneOldItems(context: ModelContext) {
        let descriptor = FetchDescriptor<ClipboardItem>(
            sortBy: [SortDescriptor(\.timestamp, order: .reverse)]
        )

        guard let allItems = try? context.fetch(descriptor) else { return }

        if allItems.count > maxItems {
            let itemsToDelete = allItems.suffix(from: maxItems)
            for item in itemsToDelete {
                context.delete(item)
            }
        }
    }
}
