import AppKit
import Observation

@Observable
class ClipboardMonitor {
    private(set) var history: [ClipboardItem] = []

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int = 0
    private var timer: DispatchSourceTimer?

    private let ignoredTypes = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        let queue = DispatchQueue(label: "com.clipass.monitor", qos: .utility)
        timer = DispatchSource.makeTimerSource(queue: queue)
        timer?.schedule(deadline: .now(), repeating: .milliseconds(500))
        timer?.setEventHandler { [weak self] in
            self?.poll()
        }
        timer?.resume()
    }

    func stop() {
        timer?.cancel()
        timer = nil
    }

    private func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // Check for ignored types (password managers, etc.)
        if let types = pasteboard.types {
            for type in types {
                if ignoredTypes.contains(type.rawValue) {
                    return // Skip secure content
                }
            }
        }

        guard let content = pasteboard.string(forType: .string) else { return }

        let sourceApp = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        let item = ClipboardItem(
            content: content,
            sourceApp: sourceApp,
            timestamp: Date()
        )

        DispatchQueue.main.async {
            self.history.insert(item, at: 0)
        }
    }
}
