import AppKit
import Observation
import SwiftData

@Observable
class ClipboardMonitor {
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int = 0
    private var timer: DispatchSourceTimer?
    private var modelContext: ModelContext?
    private var transformEngine: TransformEngine?
    private var hookEngine: HookEngine?

    // Lock to protect lastChangeCount from data races between background
    // timer queue and main queue writes (pattern adapted from exmen's
    // ScriptRunner NSLock guard).
    private let changeCountLock = NSLock()

    // Track whether the timer is currently suspended to avoid double-resume
    // crashes (matched from exmen's double-resume prevention pattern).
    private var isSuspended = false
    private let suspendLock = NSLock()

    var maxItems: Int {
        let stored = UserDefaults.standard.integer(forKey: "maxHistoryItems")
        return stored > 0 ? stored : 100  // Default 100 if not set or zero
    }

    // Cache for compiled regexes to avoid recompilation on every poll
    private var cachedPatternRegexes: [UUID: Regex<AnyRegexOutput>] = [:]

    private let ignoredTypes = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    init() {
        lastChangeCount = pasteboard.changeCount
        observeSleepWake()
    }

    // Get or compile regex for an IgnoredPattern
    private func getRegex(for pattern: IgnoredPattern) -> Regex<AnyRegexOutput>? {
        if let cached = cachedPatternRegexes[pattern.id] {
            return cached
        }
        guard let regex = try? Regex(pattern.pattern) else { return nil }
        cachedPatternRegexes[pattern.id] = regex
        return regex
    }

    // Invalidate cached regexes (call when patterns are modified)
    func invalidatePatternCache() {
        cachedPatternRegexes.removeAll()
    }

    func setModelContext(_ context: ModelContext) {
        self.modelContext = context
    }

    func setTransformEngine(_ engine: TransformEngine) {
        self.transformEngine = engine
    }

    func setHookEngine(_ engine: HookEngine) {
        self.hookEngine = engine
    }

    // MARK: - Sleep / Wake handling

    /// Subscribe to system sleep/wake notifications to safely pause and
    /// resume the polling timer. This prevents crashes caused by the timer
    /// firing into stale state immediately after wake.
    private func observeSleepWake() {
        let center = NSWorkspace.shared.notificationCenter

        center.addObserver(
            forName: NSWorkspace.willSleepNotification,
            object: nil, queue: .main
        ) { [weak self] _ in
            self?.handleSleep()
        }

        center.addObserver(
            forName: NSWorkspace.didWakeNotification,
            object: nil, queue: .main
        ) { [weak self] _ in
            self?.handleWake()
        }
    }

    private func handleSleep() {
        suspendLock.lock()
        defer { suspendLock.unlock() }

        guard !isSuspended, timer != nil else { return }
        timer?.suspend()
        isSuspended = true
    }

    private func handleWake() {
        // Refresh the change count so the first poll after wake doesn't
        // see a stale value and misfire.
        changeCountLock.lock()
        lastChangeCount = pasteboard.changeCount
        changeCountLock.unlock()

        suspendLock.lock()
        defer { suspendLock.unlock() }

        guard isSuspended, timer != nil else { return }
        timer?.resume()
        isSuspended = false
    }

    // MARK: - Timer lifecycle

    func start() {
        let queue = DispatchQueue(label: "com.clipass.monitor", qos: .utility)
        timer = DispatchSource.makeTimerSource(queue: queue)
        timer?.schedule(deadline: .now(), repeating: .milliseconds(500))
        timer?.setEventHandler { [weak self] in
            self?.poll()
        }
        timer?.resume()

        suspendLock.lock()
        isSuspended = false
        suspendLock.unlock()
    }

    func stop() {
        suspendLock.lock()
        // DispatchSource must be resumed before cancel if it is suspended,
        // otherwise it will crash.
        if isSuspended {
            timer?.resume()
            isSuspended = false
        }
        suspendLock.unlock()

        timer?.cancel()
        timer = nil
    }

    private func poll() {
        changeCountLock.lock()
        let currentChangeCount = lastChangeCount
        changeCountLock.unlock()

        let pasteboardCount = pasteboard.changeCount
        guard pasteboardCount != currentChangeCount else { return }

        changeCountLock.lock()
        lastChangeCount = pasteboardCount
        changeCountLock.unlock()

        // Check for ignored types (password managers, etc.)
        if let types = pasteboard.types {
            for type in types {
                if ignoredTypes.contains(type.rawValue) {
                    return // Skip secure content
                }
            }
        }

        guard let content = pasteboard.string(forType: .string) else { return }

        let sourceApp = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        DispatchQueue.main.async { [weak self] in
            guard let self = self, let context = self.modelContext else { return }

            // Apply transforms if engine is available
            var transformedContent = content
            if let engine = self.transformEngine {
                transformedContent = engine.transform(content, sourceApp: sourceApp)
            }

            // Update clipboard if content was transformed
            if transformedContent != content {
                self.pasteboard.clearContents()
                self.pasteboard.setString(transformedContent, forType: .string)
                // Update lastChangeCount to avoid re-polling our own change
                self.changeCountLock.lock()
                self.lastChangeCount = self.pasteboard.changeCount
                self.changeCountLock.unlock()
            }

            // Check ignored apps
            let appDescriptor = FetchDescriptor<IgnoredApp>()
            if let ignoredApps = try? context.fetch(appDescriptor),
               let sourceApp = sourceApp {
                for ignoredApp in ignoredApps where ignoredApp.isEnabled {
                    if sourceApp == ignoredApp.bundleId || sourceApp.contains(ignoredApp.bundleId) {
                        return // Skip ignored app
                    }
                }
            }

            // Check ignored patterns
            let patternDescriptor = FetchDescriptor<IgnoredPattern>()
            if let ignoredPatterns = try? context.fetch(patternDescriptor) {
                for ignoredPattern in ignoredPatterns where ignoredPattern.isEnabled {
                    if let regex = self.getRegex(for: ignoredPattern),
                       transformedContent.contains(regex) {
                        return // Skip content matching ignore pattern
                    }
                }
            }

            // Skip duplicate: check if most recent item has same content
            let descriptor = FetchDescriptor<ClipboardItem>(
                sortBy: [SortDescriptor(\.timestamp, order: .reverse)]
            )
            var fetchDescriptor = descriptor
            fetchDescriptor.fetchLimit = 1
            if let recentItems = try? context.fetch(fetchDescriptor),
               let mostRecent = recentItems.first,
               mostRecent.content == transformedContent {
                return // Skip duplicate
            }

            let item = ClipboardItem(
                content: transformedContent,
                sourceApp: sourceApp,
                timestamp: Date()
            )

            context.insert(item)

            // Prune old items if exceeding maxItems
            self.pruneOldItems(context: context)

            try? context.save()

            // Execute hooks after save
            self.hookEngine?.executeHooks(content: transformedContent, sourceApp: sourceApp)
        }
    }

    private func pruneOldItems(context: ModelContext) {
        // Only prune unpinned items — pinned items are exempt from limits
        let descriptor = FetchDescriptor<ClipboardItem>(
            predicate: #Predicate { !$0.isPinned },
            sortBy: [SortDescriptor(\.timestamp, order: .reverse)]
        )

        guard let unpinnedItems = try? context.fetch(descriptor) else { return }

        if unpinnedItems.count > maxItems {
            let itemsToDelete = unpinnedItems.suffix(from: maxItems)
            for item in itemsToDelete {
                context.delete(item)
            }
        }
    }
}
